-- Full Supabase DDL for RAG vector search (Pizzaria Dona Rosa)
-- Introspection Date: 2026-07-21T20:08:33.227153+00:00

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    metadata jsonb DEFAULT '{}'::jsonb,
    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
    embedding vector(1536)
);

CREATE INDEX IF NOT EXISTS documents_embedding_idx ON public.documents USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS documents_fts_idx ON public.documents USING gin (fts);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.documents
    FOR SELECT USING (true);

CREATE POLICY "Allow service_role full access" ON public.documents
    FOR ALL USING (auth.role() = 'service_role');

-- Definition for RPC function: hybrid_search
CREATE OR REPLACE FUNCTION public.hybrid_search(
    query_text text,
    query_embedding vector(1536),
    match_count int DEFAULT 10,
    full_text_weight float DEFAULT 1.0,
    semantic_weight float DEFAULT 1.0,
    rrf_k int DEFAULT 50
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity double precision
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH full_text AS (
        SELECT 
            d.id,
            d.content,
            d.metadata,
            ROW_NUMBER() OVER (ORDER BY ts_rank_cd(d.fts, websearch_to_tsquery('english', query_text)) DESC) AS rank_fts
        FROM public.documents d
        WHERE d.fts @@ websearch_to_tsquery('english', query_text)
        LIMIT match_count * 2
    ),
    semantic AS (
        SELECT 
            d.id,
            d.content,
            d.metadata,
            1 - (d.embedding <=> query_embedding) AS sim,
            ROW_NUMBER() OVER (ORDER BY d.embedding <=> query_embedding ASC) AS rank_sem
        FROM public.documents d
        WHERE d.embedding IS NOT NULL
        LIMIT match_count * 2
    )
    SELECT 
        coalesce(ft.id, sem.id) AS id,
        coalesce(ft.content, sem.content) AS content,
        coalesce(ft.metadata, sem.metadata) AS metadata,
        coalesce(sem.sim, 0.0)::double precision AS similarity
    FROM full_text ft
    FULL OUTER JOIN semantic sem ON ft.id = sem.id
    ORDER BY (
        coalesce(1.0 / (rrf_k + ft.rank_fts), 0.0) * full_text_weight +
        coalesce(1.0 / (rrf_k + sem.rank_sem), 0.0) * semantic_weight
    ) DESC
    LIMIT match_count;
END;
$$;

-- Definition for RPC function: match_documents
CREATE OR REPLACE FUNCTION public.match_documents(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.0,
    match_count int DEFAULT 10
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity double precision
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.id,
        d.content,
        d.metadata,
        (1 - (d.embedding <=> query_embedding))::double precision AS similarity
    FROM public.documents d
    WHERE d.embedding IS NOT NULL
      AND (1 - (d.embedding <=> query_embedding)) > match_threshold
    ORDER BY d.embedding <=> query_embedding ASC
    LIMIT match_count;
END;
$$;

