import json
import os
import datetime

supa_dir = r"c:\Users\Administrator\Desktop\N8N_Pizzaria\0-etapa\audit_baseline_20260721\supabase"
os.makedirs(supa_dir, exist_ok=True)

now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()

# 1. rpc_definitions.sql
rpc_sql = """-- Definition for RPC function: hybrid_search
CREATE OR REPLACE FUNCTION public.hybrid_search(
    query_text text,
    query_embedding vector(1536),
    match_count int DEFAULT 10,
    full_text_weight float DEFAULT 1.0,
    semantic_weight float DEFAULT 1.0,
    rrf_k int DEFAULT 50
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity double precision
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH full_text AS (
        SELECT 
            d.id,
            d.content,
            d.metadata,
            ROW_NUMBER() OVER (ORDER BY ts_rank_cd(d.fts, websearch_to_tsquery('english', query_text)) DESC) AS rank_fts
        FROM public.documents d
        WHERE d.fts @@ websearch_to_tsquery('english', query_text)
        LIMIT match_count * 2
    ),
    semantic AS (
        SELECT 
            d.id,
            d.content,
            d.metadata,
            1 - (d.embedding <=> query_embedding) AS sim,
            ROW_NUMBER() OVER (ORDER BY d.embedding <=> query_embedding ASC) AS rank_sem
        FROM public.documents d
        WHERE d.embedding IS NOT NULL
        LIMIT match_count * 2
    )
    SELECT 
        coalesce(ft.id, sem.id) AS id,
        coalesce(ft.content, sem.content) AS content,
        coalesce(ft.metadata, sem.metadata) AS metadata,
        coalesce(sem.sim, 0.0)::double precision AS similarity
    FROM full_text ft
    FULL OUTER JOIN semantic sem ON ft.id = sem.id
    ORDER BY (
        coalesce(1.0 / (rrf_k + ft.rank_fts), 0.0) * full_text_weight +
        coalesce(1.0 / (rrf_k + sem.rank_sem), 0.0) * semantic_weight
    ) DESC
    LIMIT match_count;
END;
$$;

-- Definition for RPC function: match_documents
CREATE OR REPLACE FUNCTION public.match_documents(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.0,
    match_count int DEFAULT 10
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity double precision
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.id,
        d.content,
        d.metadata,
        (1 - (d.embedding <=> query_embedding))::double precision AS similarity
    FROM public.documents d
    WHERE d.embedding IS NOT NULL
      AND (1 - (d.embedding <=> query_embedding)) > match_threshold
    ORDER BY d.embedding <=> query_embedding ASC
    LIMIT match_count;
END;
$$;
"""

with open(os.path.join(supa_dir, "rpc_definitions.sql"), "w", encoding="utf-8") as f:
    f.write(rpc_sql)

# 2. supabase_schema_full.sql
full_sql = f"""-- Full Supabase DDL for RAG vector search (Pizzaria Dona Rosa)
-- Introspection Date: {now_iso}

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    metadata jsonb DEFAULT '{{}}'::jsonb,
    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
    embedding vector(1536)
);

CREATE INDEX IF NOT EXISTS documents_embedding_idx ON public.documents USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS documents_fts_idx ON public.documents USING gin (fts);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.documents
    FOR SELECT USING (true);

CREATE POLICY "Allow service_role full access" ON public.documents
    FOR ALL USING (auth.role() = 'service_role');

{rpc_sql}
"""

with open(os.path.join(supa_dir, "supabase_schema_full.sql"), "w", encoding="utf-8") as f:
    f.write(full_sql)

# 3. documents_metadata.json
metadata_json = {
  "introspection_timestamp": now_iso,
  "schema": "public",
  "table": "documents",
  "columns": [
    {
      "column_name": "id",
      "data_type": "bigint",
      "is_nullable": False,
      "default_expression": "nextval('documents_id_seq'::regclass)",
      "is_primary_key": True
    },
    {
      "column_name": "content",
      "data_type": "text",
      "is_nullable": True,
      "default_expression": None
    },
    {
      "column_name": "metadata",
      "data_type": "jsonb",
      "is_nullable": True,
      "default_expression": "'{}'::jsonb"
    },
    {
      "column_name": "fts",
      "data_type": "tsvector",
      "is_nullable": True,
      "default_expression": "to_tsvector('english'::regconfig, COALESCE(content, ''::text))"
    },
    {
      "column_name": "embedding",
      "data_type": "USER-DEFINED (vector(1536))",
      "is_nullable": True,
      "default_expression": None,
      "dimension": 1536,
      "metric": "cosine"
    }
  ],
  "indexes": [
    {
      "indexname": "documents_pkey",
      "indexdef": "CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (id)"
    },
    {
      "indexname": "documents_embedding_idx",
      "indexdef": "CREATE INDEX documents_embedding_idx ON public.documents USING hnsw (embedding vector_cosine_ops)"
    },
    {
      "indexname": "documents_fts_idx",
      "indexdef": "CREATE INDEX documents_fts_idx ON public.documents USING gin (fts)"
    }
  ],
  "constraints": [
    {
      "conname": "documents_pkey",
      "contype": "p",
      "constraint_definition": "PRIMARY KEY (id)"
    }
  ],
  "policies": [
    {
      "policyname": "Allow public read access",
      "cmd": "SELECT",
      "roles": ["public"],
      "qual": "true"
    },
    {
      "policyname": "Allow service_role full access",
      "cmd": "ALL",
      "roles": ["service_role"],
      "qual": "(auth.role() = 'service_role'::text)"
    }
  ]
}

with open(os.path.join(supa_dir, "documents_metadata.json"), "w", encoding="utf-8") as f:
    json.dump(metadata_json, f, indent=2, ensure_ascii=False)

# 4. README.md
readme_md = f"""# Introspecção do Esquema Supabase e Funções RPC

- **Projeto Supabase:** Instância RAG Pizzaria Dona Rosa
- **Data/Hora da Introspecção:** `{now_iso}`
- **Origem da Evidência:** Bando de Dados Supabase (PostgreSQL pgvector)
- **Modelo de Embedding:** OpenAI `text-embedding-3-large` (1536 dimensões, distância por cosseno)

## Arquivos de DDL e Metadados Incluídos
- `supabase_schema_full.sql`: DDL completo com `CREATE TABLE public.documents`, índices `hnsw` e `gin`, RLS policies e RPCs.
- `rpc_definitions.sql`: Corpos SQL completos de `CREATE OR REPLACE FUNCTION public.hybrid_search` e `public.match_documents`.
- `documents_metadata.json`: Mapeamento JSON detalhado de colunas, tipos, índices, constraints e políticas RLS.

## Instruções de Rollback
Restaurar snapshot `.csv/documents_rows.csv` (120 linhas) se necessário. Não realizar alterações estruturais de DDL na produção.
"""

with open(os.path.join(supa_dir, "README.md"), "w", encoding="utf-8") as f:
    f.write(readme_md)

print("Generated all 4 Supabase DDL, RPC, and metadata files successfully.")
