import json
import os
import datetime

supa_dir = r"c:\Users\Administrator\Desktop\N8N_Pizzaria\0-etapa\audit_baseline_20260721\supabase"
os.makedirs(supa_dir, exist_ok=True)

schema_info = {
    "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    "database": "Supabase PostgreSQL (Vector / pgvector)",
    "table_documents": {
        "tableName": "documents",
        "columns": [
            {"name": "id", "type": "bigint", "primaryKey": True, "identity": True},
            {"name": "content", "type": "text", "nullable": True},
            {"name": "metadata", "type": "jsonb", "nullable": True},
            {"name": "fts", "type": "tsvector", "nullable": True, "description": "Full-text search vector for hybrid search"},
            {"name": "embedding", "type": "vector(1536)", "nullable": True, "dimension": 1536, "metric": "cosine"}
        ],
        "indexes": [
            {"name": "documents_pkey", "definition": "PRIMARY KEY (id)"},
            {"name": "documents_embedding_idx", "type": "hnsw / ivfflat", "metric": "vector_cosine_ops"},
            {"name": "documents_fts_idx", "type": "gin", "column": "fts"}
        ]
    },
    "rpc_functions": {
        "hybrid_search": {
            "function_name": "hybrid_search",
            "source_file": "hybrid-search/index.ts",
            "parameters": [
                {"name": "query_text", "type": "text", "description": "Query string for full-text search"},
                {"name": "query_embedding", "type": "vector(1536)", "description": "1536-dimensional vector generated by text-embedding-3-large"},
                {"name": "match_count", "type": "integer", "default": 10, "description": "Number of top matching documents to return"}
            ],
            "return_type": "TABLE(id bigint, content text, metadata jsonb, similarity double precision)",
            "embedding_model": "text-embedding-3-large",
            "embedding_dimension": 1536
        },
        "match_documents": {
            "function_name": "match_documents",
            "parameters": [
                {"name": "query_embedding", "type": "vector(1536)"},
                {"name": "match_threshold", "type": "float"},
                {"name": "match_count", "type": "integer"}
            ]
        }
    },
    "rollback_instructions": "O Supabase e a Edge Function hybrid-search sao recursos compartilhados somente leitura para consultas RAG. Nenhuma DDL ou RPC deve ser alterada durante os testes DEV. Em caso de necessidade de rollback de dados, restaurar as linhas da tabela documents a partir do snapshot `.csv/documents_rows.csv` (120 linhas, SHA-256: c7c034dd5367baeba7a277789dd1412e2e9c56a8badf586b8390dbe6dce8a71d)."
}

out_file = os.path.join(supa_dir, "documents_schema_and_rpc.json")
with open(out_file, "w", encoding="utf-8") as f:
    json.dump(schema_info, f, indent=2, ensure_ascii=False)

readme_file = os.path.join(supa_dir, "README.md")
readme_content = f"""# Documentação de Esquema e RPC Supabase (RAG Híbrido)

- **Data da Introspecção:** {schema_info['timestamp']}
- **Modelo de Embedding:** `text-embedding-3-large`
- **Dimensão:** `1536`
- **Métrica de Distância:** `cosine`

## Tabela `documents`
- `id` (bigint, PK)
- `content` (text)
- `metadata` (jsonb)
- `fts` (tsvector)
- `embedding` (vector(1536))

## Funções RPC Registradas
- `hybrid_search(query_text text, query_embedding vector(1536), match_count int)`
- `match_documents(query_embedding vector(1536), match_threshold float, match_count int)`

## Instruções de Rollback
Restaurar snapshot `documents_rows.csv` (120 linhas) se necessário. Não realizar alterações estruturais de DDL na produção.
"""

with open(readme_file, "w", encoding="utf-8") as f:
    f.write(readme_content)

print(f"Archived Supabase schema and RPC docs in {supa_dir}")
